# Generated by Django 5.1.6 on 2025-02-27 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ProdutoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('imagem', models.URLField(verbose_name='imagem')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preco')),
                ('id_produto', models.IntegerField(verbose_name='ID produto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_favoritos', to='api.cliente')),
            ],
            options={
                'verbose_name': 'Produto Favorito',
                'verbose_name_plural': 'Produtos Favoritos',
                'unique_together': {('cliente', 'id_produto')},
            },
        ),
    ]
