# Generated by Django 5.1.6 on 2025-02-27 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_produtofavorito_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtofavorito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_favoritos', to='api.cliente'),
        ),
    ]
